package main

import (
	"fmt"
	"regexp"
	"strings"
)

var (
	convRegex     = regexp.MustCompile(`^([a-z]+)(\(.+\))?(!)?:\ (.+)`)
	breakingRegex = regexp.MustCompile(`(?i)^BREAKING[ -]CHANGE:\s*(.+)`)
	noreplyRegex  = regexp.MustCompile(`^(?:[0-9]+\+)?([^@]+)@users\.noreply\.github\.com$`)
	coauthorRegex = regexp.MustCompile(`(?i)^Co-authored-by:\s*(.*?)\s*<([^>]+)>`)
)

var sectionOrder = []section{
	{key: "breaking", header: "### 🚨 Breaking Changes"},
	{key: "feat", header: "### ✨ Features"},
	{key: "fix", header: "### 🐛 Bug Fixes"},
	{key: "perf", header: "### ⚡ Performance"},
	{key: "docs", header: "### 📚 Documentation"},
	{key: "refactor", header: "### ♻️ Refactoring"},
	{key: "test", header: "### ✅ Tests"},
	{key: "build", header: "### 🏗️ Build"},
	{key: "ci", header: "### 👷 CI/CD"},
	{key: "sec", header: "### 🔒 Security"},
	{key: "lab", header: "### 🔬 Labs"},
	{key: "exp", header: "### 🧪 Experimental"},
	{key: "deps", header: "### 📦 Dependencies"},
	{key: "revert", header: "### ⏪ Reverts"},
	{key: "chore", header: "### 🔨 Chores"},
	{key: "style", header: "### 🎨 Style"},
	{key: "changes", header: "### 📝 Changes"},
	{key: "other", header: "### 🔧 Other"},
}

func parseCommit(c *Commit) {
	m := convRegex.FindStringSubmatch(c.Subject)
	if m != nil {
		c.Type = m[1]
		c.Scope = m[2]
		c.IsBreaking = m[3] == "!"
		c.Description = m[4]
	} else if breakingRegex.MatchString(c.Subject) {
		c.Type = "breaking"
		c.IsBreaking = true
		c.Description = breakingRegex.FindStringSubmatch(c.Subject)[1]
	} else {
		c.Type = "changes"
		c.Description = c.Subject
	}

	for _, line := range strings.Split(c.Body, "\n") {
		if bm := breakingRegex.FindStringSubmatch(line); bm != nil {
			c.IsBreaking = true
		}
	}
}

func typeToKey(t string) string {
	switch t {
	case "ci":
		return "ci"
	case "feat", "fix", "perf", "docs", "refactor", "test", "build",
		"sec", "lab", "exp", "deps", "revert", "chore", "style", "changes":
		return t
	default:
		return "other"
	}
}

func categorize(commits []Commit, excludeTypes map[string]bool, repo string) map[string][]string {
	buckets := make(map[string][]string)

	for _, c := range commits {
		parseCommit(&c)

		entryLink := fmt.Sprintf("[`%s`](https://github.com/%s/commit/%s)", c.ShortHash, repo, c.FullHash)

		contributors := c.Author
		for _, co := range c.CoAuthors {
			contributors += ", " + co
		}
		suffix := fmt.Sprintf("(%s by %s)", entryLink, contributors)

		if c.IsBreaking && c.Type != "breaking" {
			buckets["breaking"] = append(buckets["breaking"], fmt.Sprintf("- %s %s", c.Description, suffix))
		}

		key := typeToKey(c.Type)
		if excludeTypes[c.Type] {
			continue
		}
		buckets[key] = append(buckets[key], fmt.Sprintf("- %s %s", c.Description, suffix))
	}

	return buckets
}

func buildChangelog(buckets map[string][]string, header, intro string, files, insertions, deletions int) string {
	var sb strings.Builder
	sb.WriteString(header + "\n\n")
	sb.WriteString(intro + "\n\n")

	any := false
	for _, s := range sectionOrder {
		lines, ok := buckets[s.key]
		if !ok || len(lines) == 0 {
			continue
		}
		any = true
		sb.WriteString(s.header + "\n\n")
		for _, l := range lines {
			sb.WriteString(l + "\n")
		}
		sb.WriteString("\n")
	}

	if !any {
		sb.WriteString("- No changes detected\n\n")
	}

	if files > 0 {
		sb.WriteString("### 📊 Diff Stats\n\n")
		sb.WriteString("| Metric | Count |\n")
		sb.WriteString("|--------|------:|\n")
		sb.WriteString(fmt.Sprintf("| 📄 Files changed | %d |\n", files))
		sb.WriteString(fmt.Sprintf("| 🟢 Insertions | $\\color{green}\\textsf{+%d}$ |\n", insertions))
		sb.WriteString(fmt.Sprintf("| 🔴 Deletions | $\\color{red}\\textsf{-%d}$ |\n", deletions))
		sb.WriteString("\n")
	}

	sb.WriteString("---\n\n")
	sb.WriteString("<sub>🤖 Auto-generated by changelog workflow</sub>\n")
	return sb.String()
}

func extractCoauthorTrailers(body string) []string {
	var trailers []string
	for _, line := range strings.Split(body, "\n") {
		if coauthorRegex.MatchString(line) {
			trailers = append(trailers, line)
		}
	}
	return trailers
}

func parseCoauthor(trailer string) (name, email string) {
	m := coauthorRegex.FindStringSubmatch(trailer)
	if m == nil {
		return "", ""
	}
	return strings.TrimSpace(m[1]), strings.TrimSpace(m[2])
}

func formatContributor(login, name string) string {
	if login != "" {
		return fmt.Sprintf("[@%s](https://github.com/%s)", login, login)
	}
	return name
}
