package main

import (
	"fmt"
	"strings"
)

const coverageMarker = "📊 Test Coverage Report"

func buildReport(data []CoverageData) string {
	var sb strings.Builder
	sb.WriteString("## " + coverageMarker + "\n\n")

	for _, d := range data {
		sb.WriteString(fmt.Sprintf("### %s %s\n\n", d.Icon, d.Language))
		if !d.Available {
			sb.WriteString("> No coverage data available.\n\n")
			continue
		}
		missing := d.LinesTotal - d.LinesHit
		sb.WriteString("| Metric | Value |\n")
		sb.WriteString("|--------|-------|\n")
		sb.WriteString(fmt.Sprintf("| **Coverage** | **%.1f%%** |\n", d.Pct))
		sb.WriteString(fmt.Sprintf("| Lines covered | %d / %d |\n", d.LinesHit, d.LinesTotal))
		sb.WriteString(fmt.Sprintf("| Lines missing | %d |\n", missing))
		sb.WriteString("\n")
	}

	sb.WriteString("---\n\n")
	sb.WriteString("<sub>🤖 Generated by coverage workflow</sub>\n")
	return sb.String()
}
